[pr_reviewer]
enable_review_labels_effort = true
enable_auto_approval = true

[best_practices]
enable_global_best_practices = true

[github_app]
pr_commands = [
    "/describe --pr_description.final_update_message=false",
    "/improve",
    "/agentic_review"  # experimental, avert production for now.
]

push_commands = [
    "/describe",
    "/improve"
]